{"link": "https://dl.packetstormsecurity.net/papers/general/bluediot.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/sidechannel-countermeasures.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/dns-backchannel.pdf"}
{"link": "https://dl.packetstormsecurity.net/1710-exploits/DC-2017-09-002_Magento_CSRF_Stored_Cross_Site_Scripting.pdf"}
{"link": "https://dl.packetstormsecurity.net/1710-exploits/DC-2017-09-001_Magento_CSRF_Stored_Cross_Site_Scripting.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/Hacking_Oracle_From_Web_2.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/simple-inject.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/triggerwindows7.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/worms/To-kill-a-centrifuge.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/wireless/securing-wireless.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/asp-jsp.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Google_Chrome_3.0_Beta_Math.random_vulnerability.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/md5-considered-harmful.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/dns-spoofing.pdf"}
{"link": "https://dl.packetstormsecurity.net/0509-advisories/cirt-34-advisory.pdf"}
{"link": "https://dl.packetstormsecurity.net/0509-advisories/cirt-35-advisory.pdf"}
{"link": "https://dl.packetstormsecurity.net/0509-advisories/cirt-36-advisory.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/crlf-injection.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/wildcard_attacks.pdf"}
{"link": "https://dl.packetstormsecurity.net/1204-exploits/Oracle_GlassFish_Server_Multiple_XSS.pdf"}
{"link": "https://dl.packetstormsecurity.net/docs/hack/i2p-bt5.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/finding-0day.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/timing-attacks.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/clubhack/clubhack-magazine-dec2011.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/ICMP_Covert_Channel.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/clubhack/clubhack-magazine-feb2012.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/LM_vs_MD5.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/crossapp-scripting.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/crossapp-present.pdf"}
{"link": "https://dl.packetstormsecurity.net/1108-exploits/cybsec-manageengine.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/Win2000/Shatter_Redux.pdf"}
{"link": "https://dl.packetstormsecurity.net/1005-exploits/MOPS-2010-035.pdf"}
{"link": "https://dl.packetstormsecurity.net/1208-advisories/ICSA-12-228-01.pdf"}
{"link": "https://dl.packetstormsecurity.net/1107-exploits/ebay-xss.pdf"}
{"link": "http://www.net-square.com/advisory/NS-012006-ASPNET-LDAP.pdf"}
{"link": "https://dl.packetstormsecurity.net/0601-advisories/NS-012006-ASPNET-LDAP.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/VNSECON07-JA-Exploit_development.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/tactical_paper.pdf"}
{"link": "http://www.net-square.com/advisory/NS-012006-ASPNET-LDAP.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/43381/NS-012006-ASPNET-LDAP.pdf.html&title=NS-012006-ASPNET-LDAP.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/43381/NS-012006-ASPNET-LDAP.pdf.html&title=NS-012006-ASPNET-LDAP.pdf"}
{"link": "http://www.net-square.com/advisory/NS-012006-ASPNET-LDAP.pdf"}
{"link": "http://www.net-square.com/advisory/NS-012006-ASPNET-LDAP.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/unix/osstmm.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/ssh-timing.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/25257/ssh-timing.pdf.html&title=ssh-timing.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/25257/ssh-timing.pdf.html&title=ssh-timing.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/25506/promiscuous_detection_01.pdf.html&title=promiscuous_detection_01.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/25506/promiscuous_detection_01.pdf.html&title=promiscuous_detection_01.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/unix/promiscuous_detection_01.pdf"}
{"link": "https://dl.packetstormsecurity.net/0608-exploits/lesstif-advisory.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/dasar.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/webhack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/WritingSmallShellcode.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Writing_nasl_scripts.pdf"}
{"link": "https://dl.packetstormsecurity.net/groups/rosiello/writing-behind-a-buffer.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/writing-buffer-overflow-exploits-a-quick-and-basic-tutorial-part-3-seh.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/40192/WritingSmallShellcode.pdf.html&title=WritingSmallShellcode.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/40192/WritingSmallShellcode.pdf.html&title=WritingSmallShellcode.pdf"}
{"link": "https://dl.packetstormsecurity.net/1002-exploits/osTicket-1.6-RC5-ReflectedXSS.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/bypass/Top_10_Ajax_SH_v1.1.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/phpbugs-tutorial.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/bypass/WAF_Bypassing_By_RAFAYBALOCH.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/HTML5AttackVectors_RafayBaloch_UPDATED.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/presentations/HiP2k13-Burp_Pro_Tips_and_Tricks.pdf"}
{"link": "https://dl.packetstormsecurity.net/1005-exploits/bypassing-chrome.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/skypeimbot-analysis.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/469.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/advanced-crack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/fgont-lacnog2010-ipv6-security.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/call_for/gngc_athcon_re_report_june2011.pdf"}
{"link": "https://dl.packetstormsecurity.net/1107-exploits/thc-vodafone.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/30471/MeasuringDelay-Jitter-andPacketLosswithCiscoIOSSAA.pdf.html&title=MeasuringDelay,Jitter,andPacketLosswithCiscoIOSSAA.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/30471/MeasuringDelay-Jitter-andPacketLosswithCiscoIOSSAA.pdf.html&title=MeasuringDelay,Jitter,andPacketLosswithCiscoIOSSAA.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Whatsapp.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/Windows_Meterpreterless_PostExploit.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/nginx_exploit_documentation.pdf"}
{"link": "https://dl.packetstormsecurity.net/1507-advisories/openssh68-flaw.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/httpsslexposed.pdf"}
{"link": "https://dl.packetstormsecurity.net/0610-advisories/Practical_Onion_Hacking.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/50948/Practical_Onion_Hacking.pdf.html&title=Practical_Onion_Hacking.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/50948/Practical_Onion_Hacking.pdf.html&title=Practical_Onion_Hacking.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/htz/HTZ13_READ.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/virus/fun-with-ve.pdf"}
{"link": "https://dl.packetstormsecurity.net/0602-advisories/Bypass.pdf"}
{"link": "https://dl.packetstormsecurity.net/1503-advisories/OpenSSLaudit.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/create_any_directory_to_sysdba.pdf"}
{"link": "https://dl.packetstormsecurity.net/1109-advisories/wordpress-clickjack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/wordpress-themes.pdf"}
{"link": "https://dl.packetstormsecurity.net/1211-advisories/ICSA-12-271-01.pdf"}
{"link": "https://dl.packetstormsecurity.net/1010-exploits/Oracle_JRE_java_net_urlconnection_SOP_Bypass.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/Baseline_Requirements_V1.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/49945/smartstore.pdf.html&title=smartstore.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/49945/smartstore.pdf.html&title=smartstore.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/67488/An-approach-to-malware-collection-log-visualization.pdf.html&title=An-approach-to-malware-collection-log-visualization.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/67488/An-approach-to-malware-collection-log-visualization.pdf.html&title=An-approach-to-malware-collection-log-visualization.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/NDI5aster.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/ntoskrnl.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/IDS/hids/Sequence-Matching-and-Learning-in-Anomaly-Detection-for-Computer-Security.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Law-Enforcement-Provisions-Related-to-Computer-Security.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/govt/Mandiant_APT1_Report.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/m0t-krb5-08-2010.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/call_for/Hacktivity2011_CFP_en.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/security-web.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Oauth_Security_Issues_Rest_API_authentic.pdf"}
{"link": "https://dl.packetstormsecurity.net/0905-advisories/repurpose-attack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/draft-gont-timestamps-generation-00.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/tcpip-fragment.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/piratebay-unssl.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/ShellCodeForBeginners.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/voip/targeting-voip.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/arpspoofing.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/telephony-ip.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/clustering.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/pirelli-vuln.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/70664/targeting-voip.pdf.html&title=targeting-voip.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/70664/targeting-voip.pdf.html&title=targeting-voip.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/IDS/snort4-latest.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/IDS/SNORTRAN-wp.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/routers-nat.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/dlink_hnap_captcha.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/websso-final.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/apple-cross-app-report.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/Remote-Car-Hacking.pdf"}
{"link": "https://dl.packetstormsecurity.net/cellular_telephony/apple/iphone-defeat.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/bypass/bypassing-av.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/66779/Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf.html&title=Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/66779/Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf.html&title=Bypassing_VBAAC_with_HTTP_Verb_Tampering.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/35675/007.pdf.html&title=007.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/35675/007.pdf.html&title=007.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/31558/intrusion-agent.pdf.html&title=intrusion-agent.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/31558/intrusion-agent.pdf.html&title=intrusion-agent.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/31614/StackOverflow-en.pdf.html&title=StackOverflow-en.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/31614/StackOverflow-en.pdf.html&title=StackOverflow-en.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/wp-pentesters-guide-to-hacking-odata.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Abusing_Exploiting_and_Pwning_with_Firefox_Add-ons_final_dec.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/70663/oracle-assault.pdf.html&title=oracle-assault.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/70663/oracle-assault.pdf.html&title=oracle-assault.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/AveOfAttack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/rfie.pdf"}
{"link": "https://dl.packetstormsecurity.net/0708-advisories/NS-072307-XSS.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/IDS/OIR.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/lfi-paper.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/LFI_With_PHPInfo_Assitance.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/STIDS2012_T02_OltramariLebiere_CognitiveGroundedSystem.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/telco-crypto.pdf"}
{"link": "https://dl.packetstormsecurity.net/1005-exploits/cybsecironmail-access.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cheatsheets/BGP.pdf"}
{"link": "https://dl.packetstormsecurity.net/1011-advisories/tempuser-safari.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "https://dl.packetstormsecurity.net/0501-exploits/AWStatsVulnAnalysis.pdf"}
{"link": "https://dl.packetstormsecurity.net/0905-exploits/iiswebdav-bypass.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/The_Trash_Attack.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/abc.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/htz/HTZ11_READ_USEME.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/htz/htz_9-print.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/htz/htz_9.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/32992/enterprise_specific_security.sxw.pdf.html&title=enterprise_specific_security.sxw.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/32992/enterprise_specific_security.sxw.pdf.html&title=enterprise_specific_security.sxw.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/enterprise_specific_security.sxw.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/alpha.pdf"}
{"link": "https://dl.packetstormsecurity.net/0507-advisories/clamav.pdf"}
{"link": "https://dl.packetstormsecurity.net/0707-advisories/TISA2007-03-Public.pdf"}
{"link": "https://dl.packetstormsecurity.net/groups/netric/Netric-RE-partII.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/voip-security.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cryptography/SSL_comp_report2011.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub27-msiemshtml.pdf"}
{"link": "https://dl.packetstormsecurity.net/hitb04/hitb04-captain-crunch-01.pdf"}
{"link": "https://dl.packetstormsecurity.net/hitb04/hitb04-captain-crunch-02.pdf"}
{"link": "https://dl.packetstormsecurity.net/Xcon2005/Xcon2005_CoolQ.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/presentations/Scada_Trojans_Ruben_Rootedcon.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/ports.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/vulncode-exec.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub05-ifnuke.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub11-aspnuke.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/presentations/eu-14-Hafif-Reflected-File-Download-A-New-Web-Attack-Vector.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/39742/Xcon2005_SoBeIt.pdf.html&title=Xcon2005_SoBeIt.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/39742/Xcon2005_SoBeIt.pdf.html&title=Xcon2005_SoBeIt.pdf"}
{"link": "https://dl.packetstormsecurity.net/Xcon2005/Xcon2005_SoBeIt.pdf"}
{"link": "https://dl.packetstormsecurity.net/1505-exploits/copperminegallery-xssredir.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/win/RDP_exploit.pdf"}
{"link": "http://sc.openoffice.org/excelfileformat.pdf"}
{"link": "http://www.rem0te.com/public/images/vet.pdf"}
{"link": "https://dl.packetstormsecurity.net/0403-advisories/awservices.sxw.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/32865/awservices.sxw.pdf.html&title=awservices.sxw.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/32865/awservices.sxw.pdf.html&title=awservices.sxw.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cheatsheets/sqlmap-cheatsheet-1.0-SDB.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/createscanner.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/58180/TISA2007-07-Public.pdf.html&title=TISA2007-07-Public.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/58180/TISA2007-07-Public.pdf.html&title=TISA2007-07-Public.pdf"}
{"link": "https://dl.packetstormsecurity.net/0801-advisories/livelink-utf7-xss-advisory.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/63179/livelink-utf7-xss-advisory.pdf.html&title=livelink-utf7-xss-advisory.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/63179/livelink-utf7-xss-advisory.pdf.html&title=livelink-utf7-xss-advisory.pdf"}
{"link": "https://dl.packetstormsecurity.net/0903-exploits/libcurl-fileaccess.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/8in1wordpress.pdf"}
{"link": "https://dl.packetstormsecurity.net/1605-exploits/FS-Dynatrace_UEM_Cookie_Manipulation_v1.0-2016.pdf"}
{"link": "https://dl.packetstormsecurity.net/crypt/ssa/docs/ssausrmgr.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/21504/ssausrmgr.pdf.html&title=ssausrmgr.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/21504/ssausrmgr.pdf.html&title=ssausrmgr.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub21-personalnet.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/cheatsheets/Markdown.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/thehackernews/magazine-01-low.pdf"}
{"link": "https://dl.packetstormsecurity.net/0708-advisories/TISA2007-08-Public.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/58213/TISA2007-08-Public.pdf.html&title=TISA2007-08-Public.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/58213/TISA2007-08-Public.pdf.html&title=TISA2007-08-Public.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Guide-to-Facebook-Security.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/wireless/hackingwifionwindows.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/EBayAtt.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Context-Assessing_Cloud_Node_Security-Whitepaper.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/71901/exploration.pdf.html&title=exploration.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/71901/exploration.pdf.html&title=exploration.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/explotacion.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/exploiting-addons.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/exploit-writing-tutorial-part-8-win32-egg-hunt.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/artofantidetection.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/win32-shellcoding.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/protocols/intro_to_arp_spoofing.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/intro_to_shellcoding.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/Win2000/Intro_to_Win32_Exploits.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/34622/intro_to_shellcoding.pdf.html&title=intro_to_shellcoding.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/34622/intro_to_shellcoding.pdf.html&title=intro_to_shellcoding.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/24766/intro_to_arp_spoofing.pdf.html&title=intro_to_arp_spoofing.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/24766/intro_to_arp_spoofing.pdf.html&title=intro_to_arp_spoofing.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/intro-meta.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/unix/core_format_strings.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/30044/core_vulnerabilities.pdf.html&title=core_vulnerabilities.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/30044/core_vulnerabilities.pdf.html&title=core_vulnerabilities.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub07-novell.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub24-msexcelobj.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub24-msmpegdbz.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub25-visualsite.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub25-mozff.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub01-adobe.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub01-cpanel.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub02-apple.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub03-visinia.pdf"}
{"link": "https://dl.packetstormsecurity.net/1009-advisories/moaub03-trendmicro.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/paper-wdm.pdf"}
{"link": "https://dl.packetstormsecurity.net/1602-exploits/Node-js-Response-Splitting.pdf"}
{"link": "https://dl.packetstormsecurity.net/mag/digitalwhisper/DigitalWhisper87.pdf"}
{"link": "http://www.rem0te.com/public/images/symc2.pdf"}
{"link": "http://www.rem0te.com/public/images/symc2.pdf"}
{"link": "http://www.rem0te.com/public/images/symc2.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/SecureDevelopmentv06.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/SecondOrderCodeInjection.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/security-policy.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/34919/SecondOrderCodeInjection.pdf.html&title=SecondOrderCodeInjection.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/34919/SecondOrderCodeInjection.pdf.html&title=SecondOrderCodeInjection.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/26535/SecVulnsinEventDrivenSys.pdf.html&title=SecVulnsinEventDrivenSys.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/26535/SecVulnsinEventDrivenSys.pdf.html&title=SecVulnsinEventDrivenSys.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/201112268.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/presentations/ngwsp.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/virus/malware-reverse-part-1.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/Colentado_informaoes_em_WebSites.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/RemoteExploits2.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/auth-bypass.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/fuzzing-frameworks.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/webapplicationsecuritypart1.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/pentesting-with-metasploit.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/fuzzing-auatfb.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/fuzzing-wireplay.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/71089/fuzzing-auatfb.pdf.html&title=fuzzing-auatfb.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/71089/fuzzing-auatfb.pdf.html&title=fuzzing-auatfb.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/Detecting_and_Exploiting_ActiveX_Controls.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/wireless/2008-esorics.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/SNMP_injection.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/banking-flaws.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/file_sharing_security.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/71522/banking-flaws.pdf.html&title=banking-flaws.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/71522/banking-flaws.pdf.html&title=banking-flaws.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/71716/file_sharing_security.pdf.html&title=file_sharing_security.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/71716/file_sharing_security.pdf.html&title=file_sharing_security.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/71060/Detecting_and_Exploiting_ActiveX_Controls.pdf.html&title=Detecting_and_Exploiting_ActiveX_Controls.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/71060/Detecting_and_Exploiting_ActiveX_Controls.pdf.html&title=Detecting_and_Exploiting_ActiveX_Controls.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/govt/caseforseandroid.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/59062/WAFUTFF.pdf.html&title=WAFUTFF.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/59062/WAFUTFF.pdf.html&title=WAFUTFF.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/win/Windows_Vista_64bits_and_unexported_kernel_symbols.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/RogueXMLSpecific.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/xpms.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/attack/sqlinference.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/40459/xpms.pdf.html&title=xpms.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/40459/xpms.pdf.html&title=xpms.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/40460/sqlinference.pdf.html&title=sqlinference.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/40460/sqlinference.pdf.html&title=sqlinference.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/41667/database-on-xp.pdf.html&title=database-on-xp.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/41667/database-on-xp.pdf.html&title=database-on-xp.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/42128/MSN_Search_For_WebApp.pdf.html&title=MSN_Search_For_WebApp.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/42128/MSN_Search_For_WebApp.pdf.html&title=MSN_Search_For_WebApp.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/43457/aawns.pdf.html&title=aawns.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/43457/aawns.pdf.html&title=aawns.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/xss-streetfight.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/web/XSSTunnelling.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/57625/XSSTunnelling.pdf.html&title=XSSTunnelling.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/57625/XSSTunnelling.pdf.html&title=XSSTunnelling.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/sqlinjection-filtering.pdf"}
{"link": "https://dl.packetstormsecurity.net/0403-advisories/solaris_kernel_vfs.sxw.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/SQLInjectionWhitePaper.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/bypass/SQL_Injection_Evasion.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/database/sql-optimization.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/33120/SQL_Injection_Evasion.pdf.html&title=SQL_Injection_Evasion.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/33120/SQL_Injection_Evasion.pdf.html&title=SQL_Injection_Evasion.pdf"}
{"link": "https://dl.packetstormsecurity.net/1012-advisories/CA191110.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/60494/Antiphish-ITUNDERGROUND.pdf.html&title=Antiphish-ITUNDERGROUND.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/60494/Antiphish-ITUNDERGROUND.pdf.html&title=Antiphish-ITUNDERGROUND.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/68274/AntiPhishing.pdf.html&title=AntiPhishing.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/68274/AntiPhishing.pdf.html&title=AntiPhishing.pdf"}
{"link": "https://dl.packetstormsecurity.net/1408-exploits/SAS_Security_Bug.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/presentations/HackingyourDroid-Slides.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/shellcode/re_shellcode.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/HITB_Hacking_Soft_Tokens_v1.2.pdf"}
{"link": "https://dl.packetstormsecurity.net/1110-exploits/googleappenginesdk.pdf"}
{"link": "https://dl.packetstormsecurity.net/papers/general/XMLDTDEntityAttacks.pdf"}
{"link": "https://dl.packetstormsecurity.net/0501-advisories/directory_traversal.pdf"}
{"link": "http://www.corsaire.com/white-papers/040622-securing-mac-os-x.pdf"}
{"link": "https://dl.packetstormsecurity.net/0701-exploits/MOAB-06-01-2007.pdf"}
{"link": "https://www.reddit.com/submit?url=https://packetstormsecurity.com/files/53553/MOAB-06-01-2007.pdf.html&title=MOAB-06-01-2007.pdf"}
{"link": "http://www.stumbleupon.com/submit?url=https://packetstormsecurity.com/files/53553/MOAB-06-01-2007.pdf.html&title=MOAB-06-01-2007.pdf"}
